#!/usr/bin/env bash
# a bash script that translates a file from client to server

if [ "$#" -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign the parameters to variables
path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# Use scp to transfer the file to the server
scp -o StrictHostKeyChecking=no -i $path_to_ssh_key $path_to_file $username@$ip:~

# Check the exit status of the scp command
if [ $? -eq 0 ]; then
  echo "File transferred successfully."
else
  echo "File transfer failed."
fi
