#!/usr/bin/env bash
# Configure your Nginx server to redirect to another page

sudo apt-get update
sudo apt-get install -y nginx

# Configure the redirection
sudo sed -i '/^\sserver_name.*/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx start

